"""add lawyers + support messages

Revision ID: 361231ddf389
Revises: bbb83819ebe9
Create Date: 2025-12-18 14:08:15.904102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '361231ddf389'
down_revision = 'bbb83819ebe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('profile_picture_path', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lawyers_email'), ['email'], unique=False)

    op.create_table('contact_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_user_id'), ['user_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    # Safe drop: only drop if tables exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'checklist_attachments' in existing_tables:
        with op.batch_alter_table('checklist_attachments', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_checklist_attachments_item_id'))
            batch_op.drop_index(batch_op.f('ix_checklist_attachments_user_id'))
        op.drop_table('checklist_attachments')
    
    if 'checklist_progress' in existing_tables:
        with op.batch_alter_table('checklist_progress', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_checklist_progress_item_id'))
            batch_op.drop_index(batch_op.f('ix_checklist_progress_user_id'))
        op.drop_table('checklist_progress')
    
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_knowledge_sources_content_hash'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_cnic'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_cnic'))
        batch_op.create_index(batch_op.f('ix_users_cnic'), ['cnic'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['deleted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_cnic'))
        batch_op.create_index(batch_op.f('ix_users_cnic'), ['cnic'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_users_cnic'), ['cnic'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_knowledge_sources_content_hash'), ['content_hash'], unique=True)

    # Recreate tables only if they don't exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'checklist_progress' not in existing_tables:
        op.create_table('checklist_progress',
        sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column('item_id', sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('done_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], name=op.f('checklist_progress_item_id_fkey'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('checklist_progress_user_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('checklist_progress_pkey')),
        sa.UniqueConstraint('user_id', 'item_id', name=op.f('uq_checklist_progress_user_item'), postgresql_include=[], postgresql_nulls_not_distinct=False)
        )
        with op.batch_alter_table('checklist_progress', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_checklist_progress_user_id'), ['user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_checklist_progress_item_id'), ['item_id'], unique=False)

    if 'checklist_attachments' not in existing_tables:
        op.create_table('checklist_attachments',
        sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column('item_id', sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column('file_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('mimetype', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
        sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], name=op.f('checklist_attachments_item_id_fkey'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('checklist_attachments_user_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('checklist_attachments_pkey'))
        )
        with op.batch_alter_table('checklist_attachments', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_checklist_attachments_user_id'), ['user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_checklist_attachments_item_id'), ['item_id'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_user_id'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lawyers_email'))

    op.drop_table('lawyers')
    # ### end Alembic commands ###
