"""add province column to users

Revision ID: 3ca963ab6efb
Revises: 1ebf8022ad01
Create Date: 2025-12-29 14:15:19.821535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca963ab6efb'
down_revision = '1ebf8022ad01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_province'), ['province'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_province'))
        batch_op.drop_column('province')

    # ### end Alembic commands ###
