"""_add_embedding_metadata

Revision ID: 8bd8cd0fa8ad
Revises: adbcc0b6994b
Create Date: 2025-12-23 09:05:52.177984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd8cd0fa8ad'
down_revision = 'adbcc0b6994b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('embedding_dimension', sa.Integer(), nullable=True))

    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('embedding_dimension', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_column('embedding_dimension')
        batch_op.drop_column('embedding_model')

    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_column('embedding_dimension')
        batch_op.drop_column('embedding_model')

    # ### end Alembic commands ###
