"""add language to users

Revision ID: c6c34b25448e
Revises: 361231ddf389
Create Date: 2025-12-19 13:53:28.821486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c34b25448e'
down_revision = '361231ddf389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("language", sa.String(length=16), server_default="en", nullable=False)
        )

    # Defensive backfill (production-safe, idempotent)
    op.execute("UPDATE users SET language = 'en' WHERE language IS NULL")

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
